# Generated by Django 6.0.2 on 2026-02-22 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('sold', 'Sold')], default='pending', max_length=50),
        ),
    ]
