# Generated by Django 6.0.2 on 2026-02-23 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_vehicle_current_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='current_price',
        ),
    ]
