# Generated by Django 6.0.2 on 2026-02-28 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0008_alter_vehicle_vin'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclebrand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_brands/'),
        ),
    ]
